name: isce2
channels:
 - conda-forge
dependencies:
 - python=3.11
 - cython
 - numpy
 - pandas
 - geopandas
 - scipy
 - matplotlib
 - imageio
 - xarray
 - dask
 - netcdf4
 - rasterio
 - rioxarray
 - shapely
 - asf_search
 - ipykernel
 - pystac
 - pystac-client
 - boto3
 - tqdm
 - cmocean
 - pdemtools
 - jupyterlab
 - gdal
 - h5py
 - libgdal
 - pytest
 - fftw
 - basemap
 - scons
 - opencv
 - conda-build
 - isce2
 - s3fs
 - zarr
